### ISSUE TITLE
Boss position not reset when player dies

### ISSUE THREAD

**Issue by Zyanting18** [ldkjf2nd/17-18Capstone#3]
Scenario: 
During the fight with the boss, the player dies at first. After that, the player should respawn and continue fights with the boss the second time.

Bug: 
The boss position is still on the floor which should be reset on the wall.
but the camera still moved away to the beginning dialog with the boss.

<img width="2397" alt="screen_shot_2017-12-19_at_11 38 17_am" src="https://user-images.githubusercontent.com/31933239/34172646-c3c84dce-e4c0-11e7-8c8a-b965c8159913.png">

**Comment by rabbitslover** [comment]
Going to look into the bug and trying to fix it now.

Some background Info about me:
4th-year Software Eng Student at Mac.
friend of one the group member. 
been using Unity 3D for 1.5 years made 1 project with it

**Comment by rabbitslover** [comment]
The bug is because the BossTrigger value was not reset when the player died.
Looking into Scripts folder checking PlayerController.cs file.
The method intilization is where all the variable value resets all the values to their default.
So adding the following two line in the PlayerController intilization method would fix the bug.
BossTrigger.bossIntro = false;
BossTrigger.bossStart = false;

**Comment by Zyanting18** [comment]
Closing the Issue since the bug has been fixed now.
